# Site settings
title: Stas's personal page and blog
email: shershnev.stas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Practical backend development notes by Stas Shershnev. Python, MongoDB, Docker, pytest, etc.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://n1te.github.io" # the base hostname & protocol for your site
timezone: Europe/Moscow

# Build settings
markdown: kramdown
permalink: /blog/:title

# Menu
navigation:
- text: Blog
  url: /
- text: About Me
  url: /about/
